process.env.NODE_ENV ??= 'test'
process.env.PUBLIC_ORIGIN ??= 'http://localhost:5173'
process.env.DATABASE_URL ??= 'postgres://maf:maf@localhost:5432/maf_test'
process.env.REDIS_URL ??= 'redis://localhost:6379'
process.env.BETTER_AUTH_SECRET ??= 'test-secret-test-secret-test-secret-test-secret'
process.env.DAILY_SEED_SECRET ??= 'test-secret-test-secret-test-secret-test-secret'
process.env.LOG_LEVEL ??= 'error'
