import type { WordCategory, WordEntry } from './types'

const w = (word: string, category: WordCategory, vi: string, en: string): WordEntry => ({
  id: word.toLowerCase().replace(/\s+/g, '-'),
  word,
  category,
  hint: { vi, en },
})

export const WORDS: WordEntry[] = [
  w(
    'BÁNH NƯỚNG',
    'food',
    'Vỏ vàng nướng lò, nhân thập cẩm hoặc đậu xanh',
    'Baked mooncake with a golden crust',
  ),
  w('BÁNH DẺO', 'food', 'Vỏ trắng mềm dẻo, không cần nướng', 'Soft white snow-skin mooncake'),
  w(
    'THẬP CẨM',
    'food',
    'Nhân bánh truyền thống trộn nhiều loại hạt, mứt, lạp xưởng',
    'Classic mixed-nut mooncake filling',
  ),
  w('ĐẬU XANH', 'food', 'Nhân bánh màu vàng, ngọt bùi', 'Sweet yellow bean paste filling'),
  w(
    'TRỨNG MUỐI',
    'food',
    '"Mặt trăng" nằm giữa chiếc bánh',
    'The salty "moon" hidden inside a mooncake',
  ),
  w(
    'HẠT SEN',
    'food',
    'Nhân bánh thanh mát từ loài hoa mùa hè',
    "Filling made from a lotus flower's seeds",
  ),
  w(
    'CHÓ BƯỞI',
    'food',
    'Con vật xù lông làm từ tép quả có múi',
    'A fluffy "dog" sculpted from pomelo segments',
  ),
  w(
    'QUẢ HỒNG',
    'food',
    'Trái cam đỏ hay bày trên mâm cỗ mùa thu',
    'Orange autumn fruit on the festival tray',
  ),
  w(
    'MÂM CỖ',
    'food',
    'Bày bánh, trái cây chờ trăng lên',
    'Tray of treats laid out to greet the moon',
  ),
  w('TRÀ NÓNG', 'food', 'Thức uống đi cùng bánh khi ngắm trăng', 'Hot drink sipped with mooncakes'),
  w(
    'ĐÈN ÔNG SAO',
    'toy',
    'Năm cánh dán giấy bóng kính đỏ',
    'Five-pointed lantern covered in red cellophane',
  ),
  w(
    'ĐÈN KÉO QUÂN',
    'toy',
    'Lồng đèn có hình quay nhờ hơi nóng nến',
    'Lantern with figures spun by candle heat',
  ),
  w(
    'ĐÈN LỒNG',
    'toy',
    'Vật thắp sáng trẻ em cầm đi rước',
    'What children carry in the night parade',
  ),
  w('ĐÈN CÁ CHÉP', 'toy', 'Lồng đèn hình loài cá vượt vũ môn', 'Lantern shaped like a carp'),
  w('ĐÈN CÙ', 'toy', 'Lồng đèn lăn quay trên đường', 'Wheel lantern rolled along the ground'),
  w('MẶT NẠ', 'toy', 'Đeo lên mặt, làm bằng giấy bồi', 'Papier-mâché item worn on the face'),
  w(
    'TÒ HE',
    'toy',
    'Con giống nhỏ nặn từ bột gạo nhiều màu',
    'Tiny figurines moulded from coloured rice dough',
  ),
  w(
    'TRỐNG BỎI',
    'toy',
    'Trống nhỏ xoay là kêu tạch tạch',
    'Small hand-drum that rattles when twisted',
  ),
  w(
    'TIẾN SĨ GIẤY',
    'toy',
    'Ông quan giấy cầu mong học giỏi',
    'Paper scholar doll wishing for good grades',
  ),
  w(
    'ĐẦU LÂN',
    'toy',
    'Phần rực rỡ nhất của đội múa',
    'The most colourful part of the dance troupe',
  ),
  w('CHÚ CUỘI', 'legend', 'Ngồi gốc đa trên cung trăng', 'He sits under a banyan tree on the moon'),
  w(
    'HẰNG NGA',
    'legend',
    'Nàng tiên uống thuốc trường sinh',
    'The fairy who drank the elixir of immortality',
  ),
  w('THỎ NGỌC', 'legend', 'Giã thuốc bên Hằng Nga', 'Pounds medicine beside Hằng Nga'),
  w('CÂY ĐA', 'legend', 'Cây thần kéo Cuội lên trời', 'Magic tree that carried Cuội to the sky'),
  w('HẬU NGHỆ', 'legend', 'Người bắn rơi chín mặt trời', 'The archer who shot down nine suns'),
  w(
    'CHỊ HẰNG',
    'legend',
    'Cách trẻ em gọi nàng tiên trên trăng',
    "Children's affectionate name for the moon fairy",
  ),
  w('GIÃ THUỐC', 'legend', 'Việc Thỏ Ngọc làm mỗi đêm', 'What the Jade Rabbit does every night'),
  w('CUNG TRĂNG', 'legend', 'Nơi Cuội và Hằng Nga đang ở', 'Where Cuội and Hằng Nga live'),
  w('MÚA LÂN', 'activity', 'Điệu múa rộn ràng theo tiếng trống', 'Lively dance to drumbeats'),
  w(
    'ÔNG ĐỊA',
    'activity',
    'Bụng to, cầm quạt, trêu lân',
    'Big-bellied man with a fan who teases the lion',
  ),
  w(
    'RƯỚC ĐÈN',
    'activity',
    'Trẻ con nối đuôi nhau đi quanh ngõ',
    'Children walk in a line through the streets with lights',
  ),
  w(
    'PHÁ CỖ',
    'activity',
    'Cả nhà cùng ăn mâm bánh trái khi trăng lên',
    'Sharing the tray of treats once the moon is up',
  ),
  w(
    'TRÔNG TRĂNG',
    'activity',
    'Ngồi sân ngắm ánh sáng đêm rằm',
    'Sitting out to watch the full moon',
  ),
  w(
    'HÁT TRỐNG QUÂN',
    'activity',
    'Hát đối đáp dân gian mùa thu',
    'Folk call-and-response singing of autumn',
  ),
  w(
    'TRĂNG RẰM',
    'nature',
    'Tròn và sáng nhất trong tháng',
    'Roundest, brightest night of the month',
  ),
  w('THÁNG TÁM', 'nature', 'Tháng âm lịch của Tết Trung Thu', 'Lunar month of the festival'),
  w(
    'ÁNH TRĂNG',
    'nature',
    'Thứ soi sáng sân nhà đêm hội',
    'What lights the yard on festival night',
  ),
  w(
    'MÙA THU',
    'nature',
    'Mùa của lá vàng và trăng tròn',
    'Season of golden leaves and the full moon',
  ),
  w('ĐOÀN VIÊN', 'symbol', 'Ý nghĩa sum họp của ngày Tết này', "Reunion — the festival's meaning"),
  w(
    'TẾT THIẾU NHI',
    'symbol',
    'Tên gọi khác: ngày Tết của trẻ em',
    "Another name: the children's festival",
  ),
  w('ĐÊM HỘI', 'symbol', 'Đêm vui rộn ràng dưới trăng', 'Festive night under the moon'),
  w(
    'TRỐNG CƠM',
    'symbol',
    'Nhạc cụ trong bài hát dân ca quen thuộc',
    'Drum from a beloved folk song',
  ),
]
